# Site settings
title: Simon Says
tagline: Fresh Food Faster
email: info@simonsays.gg
telephone: 01234 567890
address: >
  No. 3 Commercial Arcade
  St Peter Port
  Guernsey
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonsays.gg" # the base hostname & protocol for your site
twitter_username: jekyllrb
facebook_username:  jekyll

# Build settings
markdown: kramdown
